<?php

namespace AppBundle\Repository;

/**
 * EraMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EraMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
