<?php

namespace AppBundle\Repository;

/**
 * MemberDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberDateRepository extends \Doctrine\ORM\EntityRepository
{
}
