<?php

namespace AppBundle\Repository;

/**
 * MemberMemberTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberMemberTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
