<?php

namespace AppBundle\Repository;

/**
 * TypeMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
