<?php

namespace AppBundle\Repository;

/**
 * TypeVoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeVoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
