<?php

namespace AppBundle\Repository;

/**
 * VoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoiceRepository extends \Doctrine\ORM\EntityRepository
{
}
