imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: nl

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router: 
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 1800
    fragments: ~
    http_method_override: true
    assets: ~
    templating:
        form:
            resources:
                - 'views/form'
        engines:
            twig
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/theme.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    # port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    # encryption: '%mailer_encryption%'
    #spool: { type: memory }
    # later toegevoegd om uit te proberen. Alleen hiermee doet hij het. 
    # met testen deze opties weghalen.
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false

    # FOSUserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: '%mailer_user%'
        sender_name: "Baarns mannenkoor, de Voorzitter"

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        font-awesome-eot:
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-400.eot'
            output: 'web\webfonts\fa-brands-400.eot'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-regular-400.eot'
            output: 'web\webfonts\fa-regular-400.eot'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-900.eot'
            output: 'web\webfonts\fa-brands-900.eot'
        font-awesome-svg:
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-400.svg'
            output: 'web\webfonts\fa-brands-400.svg'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-regular-400.svg'
            output: 'web\webfonts\fa-regular-400.svg'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-900.svg'
            output: 'web\webfonts\fa-brands-900.svg'
        font-awesome-ttf:
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-400.ttf'
            output: 'web\webfonts\fa-brands-400.ttf'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-regular-400.ttf'
            output: 'web\webfonts\fa-regular-400.ttf'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-900.ttf'
            output: 'web\webfonts\fa-brands-900.ttf'
        font-awesome-woff:
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-400.woff'
            output: 'web\webfonts\fa-brands-400.woff'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-regular-400.woff'
            output: 'web\webfonts\fa-regular-400.woff'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-solid-900.woff'
            output: 'web\webfonts\fa-solid-900.woff'
        font-awesome-woff2:
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-brands-400.woff2'
            output: 'web\webfonts\fa-brands-400.woff2'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-regular-400.woff2'
            output: 'web\webfonts\fa-regular-400.woff2'
            inputs: '%kernel.root_dir%/Resources/assets/webfonts/fa-solid-900.woff2'
            output: 'web\webfonts\fa-solid-900.woff2'