// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Primarytest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void Primarytest() {
    driver.get("http://localhost:8000/");
    driver.manage().window().setSize(new Dimension(1296, 1000));
    driver.findElement(By.linkText("Inloggen")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("dirk");
    driver.findElement(By.id("password")).sendKeys("dirk");
    driver.findElement(By.cssSelector(".svg-inline--fa")).click();
    driver.findElement(By.xpath("//td[@id=\'td\']/a")).click();
    js.executeScript("window.scrollTo(0,144)");
    driver.findElement(By.cssSelector(".fa-edit > path")).click();
    js.executeScript("window.scrollTo(0,700)");
    driver.findElement(By.cssSelector(".collection-item:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".grid-x:nth-child(15) .button")).click();
    driver.findElement(By.cssSelector(".fa-clipboard-list > path")).click();
    driver.findElement(By.cssSelector("li:nth-child(2) li:nth-child(1) > a")).click();
    driver.findElement(By.linkText("Help")).click();
    driver.findElement(By.linkText("voorzitter")).click();
    driver.findElement(By.id("contact_name")).click();
    driver.findElement(By.id("contact_name")).sendKeys("Dirk");
    driver.findElement(By.id("contact_email")).sendKeys("dirk@feka.nl");
    {
      WebElement dropdown = driver.findElement(By.id("contact_subject"));
      dropdown.findElement(By.xpath("//option[. = 'Persoonsgegevens']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("contact_subject"));
      dropdown.findElement(By.xpath("//option[. = 'Gebruikersgegevens']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("contact_subject"));
      dropdown.findElement(By.xpath("//option[. = 'Anders']")).click();
    }
    driver.findElement(By.id("contact_message")).sendKeys("Testen Selenium");
    driver.findElement(By.cssSelector(".button:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".button")).click();
  }
}
